<?php
defined('ABSPATH') or die('No direct access');
if (!current_user_can('manage_options')) { wp_die('Permisos insuficientes.', 'Error', ['response' => 403]); }
if (!class_exists('CanonicalFreeRepository')) require_once dirname(__DIR__, 3) . '/repositories/CanonicalFreeRepository.php';
$repo = new CanonicalFreeRepository();
$view = isset($_GET['view']) ? sanitize_key(wp_unslash($_GET['view'])) : '';
$container_id = isset($_GET['container_id']) ? (int) $_GET['container_id'] : 0;
$nonce = wp_create_nonce('aa_canonical_free');
$base = admin_url('admin-post.php?action=aa_iframe_content&module=canonical_shell');
?>
<section class="mx-auto max-w-5xl p-4" data-aa-canonical-free="1">
<?php if ($view === 'records' && $container_id > 0) : $list=$repo->list($container_id); if (!$list) : ?>
  <div class="rounded-lg bg-red-50 p-4 text-red-700">La lista no existe.</div>
<?php else : ?>
  <div class="mb-5 flex items-center justify-between gap-3"><div><a class="text-sm text-indigo-700 hover:underline" href="<?php echo esc_url($base); ?>">← Todas las listas</a><h1 class="mt-1 text-xl font-semibold text-gray-900"><?php echo esc_html($list['title']); ?></h1></div></div>
  <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="mb-5 rounded-xl bg-white p-4 shadow-sm">
    <input type="hidden" name="action" value="aa_canonical_free_save_record"><input type="hidden" name="_wpnonce" value="<?php echo esc_attr($nonce); ?>"><input type="hidden" name="container_id" value="<?php echo (int)$container_id; ?>">
    <label class="block text-sm font-medium">Nuevo registro <input required name="title" class="mt-1 w-full rounded border border-gray-300 p-2" maxlength="200"></label>
    <label class="mt-3 block text-sm font-medium">Detalles <textarea name="details" class="mt-1 w-full rounded border border-gray-300 p-2"></textarea></label>
    <button class="mt-3 rounded bg-indigo-600 px-4 py-2 font-semibold text-white">Crear registro</button>
  </form>
  <div class="space-y-3"><?php foreach ($repo->records($container_id) as $record) : ?><article class="rounded-xl bg-white p-4 shadow-sm"><div class="flex justify-between gap-3"><div><h2 class="font-semibold text-gray-900"><?php echo esc_html($record['title']); ?></h2><?php if ($record['details']) : ?><p class="mt-1 whitespace-pre-wrap text-sm text-gray-600"><?php echo esc_html($record['details']); ?></p><?php endif; ?></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="aa_canonical_free_delete_record"><input type="hidden" name="_wpnonce" value="<?php echo esc_attr($nonce); ?>"><input type="hidden" name="container_id" value="<?php echo (int)$container_id; ?>"><input type="hidden" name="id" value="<?php echo (int)$record['id']; ?>"><button class="text-sm text-red-700">Eliminar</button></form></div><details class="mt-3"><summary class="cursor-pointer text-sm text-indigo-700">Editar</summary><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="mt-2"><input type="hidden" name="action" value="aa_canonical_free_save_record"><input type="hidden" name="_wpnonce" value="<?php echo esc_attr($nonce); ?>"><input type="hidden" name="container_id" value="<?php echo (int)$container_id; ?>"><input type="hidden" name="id" value="<?php echo (int)$record['id']; ?>"><input required name="title" value="<?php echo esc_attr($record['title']); ?>" class="w-full rounded border p-2"><textarea name="details" class="mt-2 w-full rounded border p-2"><?php echo esc_textarea($record['details']); ?></textarea><button class="mt-2 text-sm text-indigo-700">Guardar</button></form></details></article><?php endforeach; ?></div>
<?php endif; else : ?>
  <div class="mb-5 flex items-center justify-between"><h1 class="text-xl font-semibold text-gray-900">Todas las listas</h1></div>
  <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="mb-5 rounded-xl bg-white p-4 shadow-sm"><input type="hidden" name="action" value="aa_canonical_free_save_list"><input type="hidden" name="_wpnonce" value="<?php echo esc_attr($nonce); ?>"><label class="block text-sm font-medium">Nueva lista <input required name="title" class="mt-1 w-full rounded border border-gray-300 p-2" maxlength="200"></label><label class="mt-3 block text-sm font-medium">Detalles <textarea name="details" class="mt-1 w-full rounded border border-gray-300 p-2"></textarea></label><button class="mt-3 rounded bg-indigo-600 px-4 py-2 font-semibold text-white">Crear lista</button></form>
  <div class="space-y-3"><?php foreach ($repo->lists() as $list) : $url=add_query_arg(['view'=>'records','container_id'=>(int)$list['id']],$base); ?><article class="rounded-xl bg-white p-4 shadow-sm"><div class="flex justify-between gap-3"><div><a class="font-semibold text-indigo-700 hover:underline" href="<?php echo esc_url($url); ?>"><?php echo esc_html($list['title']); ?></a><?php if ($list['details']) : ?><p class="mt-1 whitespace-pre-wrap text-sm text-gray-600"><?php echo esc_html($list['details']); ?></p><?php endif; ?></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="aa_canonical_free_delete_list"><input type="hidden" name="_wpnonce" value="<?php echo esc_attr($nonce); ?>"><input type="hidden" name="id" value="<?php echo (int)$list['id']; ?>"><button class="text-sm text-red-700">Eliminar</button></form></div><details class="mt-3"><summary class="cursor-pointer text-sm text-indigo-700">Editar</summary><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="mt-2"><input type="hidden" name="action" value="aa_canonical_free_save_list"><input type="hidden" name="_wpnonce" value="<?php echo esc_attr($nonce); ?>"><input type="hidden" name="id" value="<?php echo (int)$list['id']; ?>"><input required name="title" value="<?php echo esc_attr($list['title']); ?>" class="w-full rounded border p-2"><textarea name="details" class="mt-2 w-full rounded border p-2"><?php echo esc_textarea($list['details']); ?></textarea><button class="mt-2 text-sm text-indigo-700">Guardar</button></form></details></article><?php endforeach; ?></div>
<?php endif; ?>
</section>
